### ISSUE TITLE
Tabs in the settings window are unreadable in light theme

### ISSUE THREAD

**Issue by eritbh** [GooseMod/OpenAsar#148]
Related to #92

![image](https://github.com/GooseMod/OpenAsar/assets/4165301/bfb8e532-9343-4a62-8368-0c5133ed6d74)

A quick CSS fix, tested in the inspector, though this does also make the inactive tab text a bit dimmer in dark mode:

```css
header > div {
  color: var(--text-muted);
}
header > div.active {
  color: inherit;
}
```

![image](https://github.com/GooseMod/OpenAsar/assets/4165301/fcebc2c7-b291-44ee-9138-44a54c1f98d9)
![image](https://github.com/GooseMod/OpenAsar/assets/4165301/f370f156-2702-4714-9cda-ef0728d045fa)

It doesn't look like the content of this window is actually in this repo, since it's pulled in from an external page I couldn't track down a repo for, so I can't submit a PR to fix this - hopefully this is something that can be patched easily on your end.
