### ISSUE TITLE
Custom CSS not applied

### ISSUE THREAD

**Issue by ISSOtm** [GooseMod/OpenAsar#83]
I want to apply the following CSS rule:
```css
[class|=chatContent] [class|=buttons] > :not(:last-child) {
    display: none;
}
```
(This hides all buttons in the chat bar except the emoji picker, saving valuable horizontal space.)

If I inject this via the Inspector, it works; but if I paste it in OpenAsar's `Theming` panel, nothing happens. (I can see it in the config file, but the rule doesn't appear to be applied.) Do you know why? Thanks!
